### ISSUE TITLE
Handle deprecated set-output

### ISSUE THREAD

**Issue by Firehed** [Firehed/multistage-docker-build-action#28]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by gonuke** [comment]
I'm still seeing the warning associated with this in my builds:

[multistage_image_build (20.04)](https://github.com/bquan0/pyne/actions/runs/3934755998/jobs/6729783027#step:13:20)
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
